### ISSUE TITLE
No module named yelp.settings

### ISSUE THREAD

**Issue by ZachHandley** [RavenHustler/yelp-data-scraper#1]
Howdy,

I reallllllly appreciate you writing this, incredibly useful, I have an error where it says it no module named yelp.settings, any idea why?

**Comment by ZachHandley** [comment]
Fixed it, needed a __init__.py blank file in the yelp folder <3

**Comment by Gillinghammer** [comment]
I've added the init.py inside the yelp folder but my issue continues to persist

> ~/yelpscraper(master*) » scrapy                                                                                                                              user@user
> Traceback (most recent call last):
>   File "/usr/local/bin/scrapy", line 11, in <module>
>     sys.exit(execute())
>   File "/usr/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 109, in execute
>     settings = get_project_settings()
>   File "/usr/local/lib/python2.7/site-packages/scrapy/utils/project.py", line 68, in get_project_settings
>     settings.setmodule(settings_module_path, priority='project')
>   File "/usr/local/lib/python2.7/site-packages/scrapy/settings/__init__.py", line 292, in setmodule
>     module = import_module(module)
>   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
>     __import__(name)
> ImportError: No module named yelp.settings

**Comment by Gillinghammer** [comment]
adding some detail... looks like the pip install -r requirements.txt command fails when installing ### **pypiwin32**

> Collecting pypiwin32==219 (from -r requirements.txt (line 20))
>   Downloading https://files.pythonhosted.org/packages/2b/ca/5c086c18de8f70222787b3e824e755b68d99272531522e77bb381d4f60c8/pypiwin32-219.zip (4.8M
> B)
>     100% |████████████████████████████████| 4.8MB 163kB/s 
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-9eAQsv/pypiwin32/setup.py", line 83, in <module>
>         import _winreg
>     ImportError: No module named _winreg
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9eAQsv/pypiwin32/


Any ideas why? I've tried to get this running on my local mac, remote ubuntu server and pythonanywhere getting stuck at the same place

**Comment by day1dan** [comment]
@Gillinghammer I've been working on this as well. Seems as though there's a Win requirement and I'm on Mac. I was able to bypass the Win Registry (no idea if that helps or hurts in the long run - I'm a noob to Python) by opening the _requirements.txt_ file and deleting the line _pypiwin32==219_.

With that taken care of, I still see the yelp.settings issue, so I checked all the files and found a reference in scrapy.cgf line 6:
> [settings]
> default = yelp.settings

Still working on a resolution here...seems like the code doesn't recognize the file for some reason. Lmk if you figure something out?

**Comment by day1dan** [comment]
**UPDATE and FIX!**

**ITEM 1**
@Gillinghammer @IAmDragon Got to the next step - I upgraded scrapy by using 
_sudo pip install --upgrade scrapy_

Heads up that the upgrade installer REMOVED the former version of scrapy and moved the file to another folder. So I had to move it back after it installed or the scrapy command would not recognize the scrapy file. Note that where it says **xxxx** enter your computer username.

The upgraded version of scrapy needs to be moved from _/usr/local/bin/scrapy/_ to _/Users/xxxx/Library/Python/2.7/bin/_

After doing this I ran the cd yelpscraper then scrapy crawl.... command with the JSON command at the end and it works! 

**ITEM 2**
I took @Gillinghammer 's advice however the Init file needs to be _init_.py or it won't be read properly. There needs to be one _init_.py in the yelpscraper folder and one _init_.py file in the yelp folder, both blank.

The only issue I have now is that it's only showing me 10 people max rather than the whole grouping. Any thoughts?
